import json
import math

import pytest

from workingset import model as M
from workingset.config import RunConfig, load_config
from workingset.predict import predict


def test_defaults_round_trip_toml(tmp_path):
    cfg = RunConfig()
    p = tmp_path / "workingset.toml"
    p.write_text(cfg.dumps("toml"))
    assert load_config(p) == cfg


def test_defaults_round_trip_json(tmp_path):
    cfg = RunConfig()
    p = tmp_path / "workingset.json"
    p.write_text(cfg.dumps("json"))
    assert load_config(p) == cfg


def test_unknown_key_rejected():
    with pytest.raises(ValueError, match="unknown key workload.foo"):
        RunConfig.from_dict({"workload": {"foo": 1}})
    with pytest.raises(ValueError, match="unknown top-level"):
        RunConfig.from_dict({"nope": {}})


def test_schema_version_gate():
    with pytest.raises(ValueError, match="schema_version"):
        RunConfig.from_dict({"schema_version": 99})


def test_default_workload_matches_model_defaults():
    """The config's defaults ARE the study's measured defaults, field by field."""
    wl = RunConfig().to_workload()
    ref = M.Workload()
    for f in ("user_median", "user_sigma", "sub_median", "sub_sigma", "sub_ratio",
              "sys_user", "sys_sub", "sub_shares_prefix", "invalidation", "cap"):
        assert getattr(wl, f) == getattr(ref, f), f


def test_dtype_gate_raises_on_hopper_nvfp4():
    cfg = RunConfig.from_dict({"deployment": {"model": "27B", "gpu": "H200",
                                              "weight_dtype": "nvfp4"}})
    with pytest.raises(Exception):
        cfg.validate()


def test_legacy_harness_config_block(tmp_path):
    """An explorer-generated validate_deployment.py still loads."""
    block = {
        "endpoint": {"base_url": "http://x/v1", "model": "m", "api_key_env": "K"},
        "deployment": {"gpus": "4xH200", "tensor_parallel": 4, "replicas": 1,
                       "max_num_batched_tokens": 4096, "max_model_len": 180000},
        "workload": {"system_prefix_tokens": 15000, "user_prompt_median_tokens": 31000,
                     "user_prompt_sigma": 0.81, "warm_turn_tokens": 2000,
                     "think_time_s": 30.0, "subagent_ratio": 0.1,
                     "subagent_median_tokens": 8000, "subagent_sigma": 0.9,
                     "miss_rate": 0.01, "max_output_tokens": 400,
                     "context_cap_tokens": 180000, "subagent_prefix_tokens": 3000,
                     "sub_shares_prefix": False},
        "slo": {"ttft_budget_s": 10.0, "itl_floor_tok_s": 40, "percentile": 95},
        "predictions": {"warm_capacity_p5": 403},
        "hypotheses": ["H-cache: ..."],
    }
    src = ('# --- BEGIN CONFIG (generated by the interactive explorer) ---\n'
           'CONFIG = json.loads(r"""\n' + json.dumps(block, indent=4) +
           '\n""")\n# --- END CONFIG ---\n')
    p = tmp_path / "validate_deployment.py"
    p.write_text(src)
    cfg = load_config(p)
    assert cfg.deployment.gpu == "H200"
    assert cfg.deployment.tensor_parallel == 4
    assert cfg.deployment.max_num_batched_tokens == 4096
    assert cfg.deployment.max_model_len == 180000
    assert cfg.workload.miss_rate == 0.01
    assert cfg.endpoint.base_url == "http://x/v1"


def test_predict_reference_row():
    """27B / 4xH200 TP4 at the measured workload: the explorer's reference
    example (harness CONFIG comment) says cache binds near 403 users."""
    cfg = RunConfig.from_dict({"deployment": {"model": "27B", "gpu": "H200",
                                              "tensor_parallel": 4,
                                              "max_num_batched_tokens": 4096}})
    p = predict(cfg, n_iter=300)
    assert p.binding_constraint in ("cache", "decode")
    assert 350 <= p.warm_capacity_p5 <= 460
    assert p.predicted_limit_users == min(p.warm_capacity_p5, p.decode_ceiling_users,
                                          p.latency_ceiling_users,
                                          p.saturation_ceiling_users)
    assert 0 < p.prefill_duty < 1
    assert math.isfinite(p.ttft_miss_s) and p.ttft_miss_s > p.ttft_hit_s
    assert p.bstar_misses > 0
    assert p.replicas == 1


def test_predict_dp_system_multiplies():
    cfg = RunConfig.from_dict({"deployment": {"model": "35BA3B", "gpu": "H200",
                                              "tensor_parallel": 1, "replicas": 2}})
    p = predict(cfg, n_iter=200)
    assert p.replicas == 2
    assert p.system()["warm_capacity_p5"] == 2 * p.warm_capacity_p5
