import json
import math
import tomllib
from dataclasses import fields as dataclass_fields
from pathlib import Path

import pytest

from workingset import cli, model as M
from workingset.config import (SLO, Calibration, Deployment, Endpoint, RunConfig,
                               WorkloadCfg, load_config)
from workingset.predict import predict


def test_defaults_round_trip_toml(tmp_path):
    cfg = RunConfig()
    p = tmp_path / "workingset.toml"
    p.write_text(cfg.dumps("toml"))
    assert load_config(p) == cfg


def test_defaults_round_trip_json(tmp_path):
    cfg = RunConfig()
    p = tmp_path / "workingset.json"
    p.write_text(cfg.dumps("json"))
    assert load_config(p) == cfg


def test_headcount_round_trip_and_dp_conversion(tmp_path):
    cfg = RunConfig.from_dict({
        "deployment": {"replicas": 8},
        "workload": {"headcount": 2000, "peak_active_share": 0.35,
                     "sessions_per_active_user": 2.0},
    })
    assert cfg.workload.users is None
    assert cfg.users_per_group() == 175
    text = cfg.dumps("toml")
    assert "headcount = 2000" in text and "users =" not in text
    p = tmp_path / "headcount.toml"
    p.write_text(text)
    assert load_config(p) == cfg


def test_headcount_and_users_are_mutually_exclusive():
    cfg = RunConfig.from_dict({"workload": {"headcount": 2000, "users": 175}})
    with pytest.raises(ValueError, match="cannot both be set"):
        cfg.validate()


@pytest.mark.parametrize("workload, message", [
    ({"headcount": -1}, "headcount must be >= 0"),
    ({"headcount": 1, "peak_active_share": 0}, "peak_active_share"),
    ({"headcount": 1, "peak_active_share": 1.01}, "peak_active_share"),
    ({"headcount": 1, "sessions_per_active_user": 0.9}, "sessions_per_active_user"),
])
def test_headcount_inputs_are_validated(workload, message):
    with pytest.raises(ValueError, match=message):
        RunConfig.from_dict({"workload": workload}).validate()


def test_unknown_key_rejected():
    with pytest.raises(ValueError, match="unknown key workload.foo"):
        RunConfig.from_dict({"workload": {"foo": 1}})
    with pytest.raises(ValueError, match="unknown top-level"):
        RunConfig.from_dict({"nope": {}})


def test_schema_version_gate():
    with pytest.raises(ValueError, match="schema_version"):
        RunConfig.from_dict({"schema_version": 99})


def test_default_workload_matches_model_defaults():
    """The config's defaults ARE the study's measured defaults, field by field."""
    wl = RunConfig().to_workload()
    ref = M.Workload()
    for f in ("user_median", "user_sigma", "sub_median", "sub_sigma", "sub_ratio",
              "sys_user", "sys_sub", "sub_shares_prefix", "invalidation", "cap"):
        assert getattr(wl, f) == getattr(ref, f), f


def test_dtype_gate_raises_on_hopper_nvfp4():
    cfg = RunConfig.from_dict({"deployment": {"model": "27B", "gpu": "H200",
                                              "weight_dtype": "nvfp4"}})
    with pytest.raises(Exception):
        cfg.validate()


def test_legacy_harness_config_block(tmp_path):
    """An explorer-generated harness download still loads."""
    block = {
        "endpoint": {"base_url": "http://x/v1", "model": "m", "api_key_env": "K"},
        "deployment": {"gpus": "4xH200", "tensor_parallel": 4, "replicas": 1,
                       "max_num_batched_tokens": 4096, "max_model_len": 180000},
        "workload": {"system_prefix_tokens": 15000, "user_prompt_median_tokens": 31000,
                     "user_prompt_sigma": 0.81, "warm_turn_tokens": 2000,
                     "think_time_s": 30.0, "subagent_ratio": 0.1,
                     "subagent_median_tokens": 8000, "subagent_sigma": 0.9,
                     "miss_rate": 0.01, "max_output_tokens": 400,
                     "context_cap_tokens": 180000, "subagent_prefix_tokens": 3000,
                     "sub_shares_prefix": False},
        "slo": {"ttft_budget_s": 10.0, "itl_floor_tok_s": 40, "percentile": 95},
        "predictions": {"warm_capacity_p5": 403},
        "hypotheses": ["H-cache: ..."],
    }
    src = ('# --- BEGIN CONFIG (generated by the interactive explorer) ---\n'
           'CONFIG = json.loads(r"""\n' + json.dumps(block, indent=4) +
           '\n""")\n# --- END CONFIG ---\n')
    p = tmp_path / "downloaded_harness.py"
    p.write_text(src)
    cfg = load_config(p)
    assert cfg.deployment.gpu == "H200"
    assert cfg.deployment.tensor_parallel == 4
    assert cfg.deployment.max_num_batched_tokens == 4096
    assert cfg.deployment.max_model_len == 180000
    assert cfg.workload.miss_rate == 0.01
    assert cfg.endpoint.base_url == "http://x/v1"
    # the harness names only the served checkpoint: no model key is guessed
    assert cfg.deployment.model is None
    with pytest.raises(ValueError, match="pass --model"):
        cfg.validate()
    with pytest.raises(ValueError, match="model"):
        cfg.dumps("toml")
    # the load the predictions were computed at is the operating point
    block["predictions"]["operating_point_users"] = 400
    p.write_text('CONFIG = json.loads(r"""\n' + json.dumps(block, indent=4) + '\n""")\n')
    assert load_config(p).workload.users == 400


def test_committed_harness_template_loads():
    """The retired harness carried a dict-literal CONFIG (comments, 4_096
    underscores). Downloads of it are still out there, so the reference
    example must load and, given the model key, price."""
    src = Path(__file__).resolve().parent / "fixtures" / "legacy_harness.py"
    cfg = load_config(src)
    assert cfg.deployment.model is None
    assert cfg.deployment.tensor_parallel == 4
    assert cfg.deployment.max_num_batched_tokens == 4096
    from dataclasses import replace
    cfg = replace(cfg, deployment=replace(cfg.deployment, model="27B"))
    cfg.validate()


def test_explorer_toml_round_trips():
    """The explorer's own output, downloaded from the page and kept verbatim.

    `workingsetConfig` in interactive/src/harness.js writes these field names
    from the live controls; this is the assertion that the two sides still
    agree. DP2 at 200 users with a 512 GiB offload buffer, so the per-group
    conversions are exercised: users 200/2, ram_gib 512/2.
    """
    p = Path(__file__).resolve().parent / "fixtures" / "explorer_workingset.toml"
    cfg = load_config(p)
    d, w, slo, ep, cal = (cfg.deployment, cfg.workload, cfg.slo,
                          cfg.endpoint, cfg.calibration)
    assert (d.model, d.gpu) == ("35BA3B", "H200")
    assert (d.tensor_parallel, d.replicas) == (1, 2)
    assert (d.weight_dtype, d.kv_dtype) == ("fp8", "fp8")
    assert d.max_num_batched_tokens == 32_768 and d.max_model_len == 180_000
    assert d.ram_gib == 256                        # 512 GiB shared / 2 groups
    assert d.gpus == "2xH200"
    assert w.users == 100                          # 200 users / 2 groups
    assert (w.system_prefix_tokens, w.user_prompt_median_tokens) == (15_000, 31_000)
    assert (w.user_prompt_sigma, w.subagent_sigma) == (0.81, 0.9)
    assert (w.warm_turn_tokens, w.max_output_tokens) == (2_000, 400)
    assert (w.think_time_s, w.miss_rate, w.subagent_ratio) == (30, 0.01, 0.1)
    assert (w.subagent_median_tokens, w.subagent_prefix_tokens) == (8_000, 3_000)
    assert w.sub_shares_prefix is False
    assert (slo.ttft_budget_s, slo.itl_floor_tok_s, slo.percentile) == (10, 40, 95)
    assert ep.base_url == "http://localhost:8000/v1" and ep.api_key_env == "VLLM_API_KEY"
    assert (cal.mfu, cal.mbu) == (M.MFU_DEFAULT, M.MBU_DEFAULT)
    # the three knobs that used to be dropped: written even at their defaults,
    # and mtp written as the number on screen rather than left implicit
    assert (d.recurrent_state_dtype, d.weight_overhead) == ("bf16", 0)
    assert cal.mtp == M.MODELS["35BA3B"].mtp
    cfg.validate()
    # no predictions travel in the file, and re-dumping it changes nothing
    assert load_config(p) == RunConfig.from_dict(tomllib.loads(cfg.dumps("toml")))


def test_explorer_toml_names_every_field():
    """A field added to RunConfig and not to the explorer's writer would give
    users a config whose defaults silently differ from what they set."""
    p = Path(__file__).resolve().parent / "fixtures" / "explorer_workingset.toml"
    raw = tomllib.loads(p.read_text(encoding="utf-8"))
    for block, typ in (("deployment", Deployment), ("workload", WorkloadCfg),
                       ("slo", SLO), ("endpoint", Endpoint),
                       ("calibration", Calibration)):
        want = {f.name for f in dataclass_fields(typ)}
        want -= {"metrics_url"}          # optional: no /metrics on the page
        if block == "workload":
            want -= {"headcount", "peak_active_share", "sessions_per_active_user"}
        assert want == set(raw[block]), f"{block}: {want ^ set(raw[block])}"


def test_explorer_headcount_toml_names_population_fields():
    p = Path(__file__).resolve().parent / "fixtures" / "explorer_headcount.toml"
    raw = tomllib.loads(p.read_text(encoding="utf-8"))
    assert raw["workload"]["headcount"] == 400
    assert raw["workload"]["peak_active_share"] == 0.4
    assert raw["workload"]["sessions_per_active_user"] == 2
    assert "users" not in raw["workload"]
    cfg = load_config(p)
    assert cfg.users_per_group() == 40
    cfg.validate()


# ---------------------------------------------------------------------------
# The three explorer knobs the config used to drop: fp32 recurrent state,
# +15% deployed weights, and the MTP speedup. Each moves numbers on the page,
# so each has to move the same numbers here. The fixtures are real downloads
# taken at the states quoted in the comments; tests/js/explorer_config.test.mjs
# holds them to what `workingsetConfig` emits for their own share URLs.
# ---------------------------------------------------------------------------
KNOBS = "explorer_knobs_%s.toml"


def _knob(name: str):
    return load_config(Path(__file__).resolve().parent / "fixtures" / (KNOBS % name))


def test_explorer_knobs_reach_the_model():
    """35B-A3B on 1xH200, one knob at a time, against what the page reports."""
    base, fp32 = _knob("base").to_model(), _knob("fp32").to_model()
    p15, mtp10 = _knob("p15").to_model(), _knob("mtp10").to_model()
    ref = M.MODELS["35BA3B"]
    # fp32 doubles the per-session recurrent state (render.js modelFor)
    assert base.deltanet_state == ref.deltanet_state
    assert fp32.deltanet_state == 2 * ref.deltanet_state
    assert "[fp32 state]" in fp32.name
    # +15% raises the resident weight bytes, and nothing else
    assert p15.w_resident == pytest.approx(ref.w_resident * 1.15)
    assert p15.deltanet_state == ref.deltanet_state
    assert "[+15% weights]" in p15.name
    # the MTP slider overrides the model's own value
    assert base.mtp == ref.mtp and mtp10.mtp == 1.0


def test_fp32_state_costs_warm_capacity_as_the_page_reports():
    """The page's warm p50 for these two states is 281 -> 252 sessions
    (35B-A3B, 1xH200, defaults). The per-session charge is the doubled
    recurrent state, so the whole effect is that one field."""
    out = {}
    for name in ("base", "fp32"):
        cfg = _knob(name)
        _, p50, _ = M.warm_capacity(cfg.to_model(), cfg.to_topology(),
                                    cfg.to_workload(), n_iter=400, seed=0,
                                    which="all")
        out[name] = p50
    assert 276 <= out["base"] <= 286        # page 281
    assert 248 <= out["fp32"] <= 258        # page 252
    assert out["fp32"] < out["base"]


def test_weight_overhead_shrinks_the_kv_pool_as_the_page_reports():
    """The page's KV pool for these two states is 8,417,102 -> 7,897,082
    tokens. Closed form on both sides, so this is exact, not a band."""
    pool = {n: M.kv_pool_tokens(_knob(n).to_model(), _knob(n).to_topology())
            for n in ("base", "p15")}
    assert pool["base"] == pytest.approx(8_417_102.005, abs=0.01)
    assert pool["p15"] == pytest.approx(7_897_082.474, abs=0.01)


def test_mtp_override_moves_the_decode_ceiling():
    """Per-user decode is mtp x bandwidth / step bytes, so dropping the 1.7x
    speedup to 1.0 has to drop the decode ceiling with it — the page goes
    28 -> 16 users at this state."""
    base = predict(_knob("base"), n_iter=400)
    off = predict(_knob("mtp10"), n_iter=400)
    assert off.decode_ceiling_users < base.decode_ceiling_users
    assert 0.45 < off.decode_ceiling_users / base.decode_ceiling_users < 0.65
    # nothing else about the deployment moved
    assert off.warm_capacity_p5 == pytest.approx(base.warm_capacity_p5, rel=0.05)


def test_knob_round_trip_with_non_default_values():
    cfg = RunConfig.from_dict({
        "deployment": {"model": "35BA3B", "gpu": "H200",
                       "recurrent_state_dtype": "fp32", "weight_overhead": 0.15},
        "calibration": {"mtp": 1.0}})
    cfg.validate()
    back = RunConfig.from_dict(tomllib.loads(cfg.dumps("toml")))
    assert back == cfg
    assert back.deployment.recurrent_state_dtype == "fp32"
    assert back.deployment.weight_overhead == 0.15
    assert back.calibration.mtp == 1.0
    # a config that does not name mtp gets the model's own value, and says so
    # by omitting the key rather than by writing a wrong number
    plain = RunConfig.from_dict({"deployment": {"model": "35BA3B"}})
    assert plain.calibration.mtp is None
    assert "mtp" not in plain.dumps("toml")
    assert plain.to_model().mtp == M.MODELS["35BA3B"].mtp


def test_knob_gates_are_refusals_not_no_ops():
    """The explorer disables these controls (main.js enforceConstraints); at
    the file boundary they raise, so a hand-written config cannot ask for a
    knob that would silently do nothing."""
    with pytest.raises(ValueError, match="no bf16 recurrent state"):
        RunConfig.from_dict({"deployment": {"model": "MM35", "gpu": "H200",
                                            "tensor_parallel": 8,
                                            "recurrent_state_dtype": "fp32"}}).validate()
    with pytest.raises(ValueError, match="weight_overhead does not apply"):
        RunConfig.from_dict({"deployment": {"model": "27B", "gpu": "H200",
                                            "weight_overhead": 0.15}}).validate()
    with pytest.raises(ValueError, match="recurrent_state_dtype must be"):
        RunConfig.from_dict({"deployment": {"model": "27B",
                                            "recurrent_state_dtype": "bf32"}}).validate()
    with pytest.raises(ValueError, match="weight_overhead must be >= 0"):
        RunConfig.from_dict({"deployment": {"model": "35BA3B",
                                            "weight_overhead": -0.1}}).validate()
    with pytest.raises(ValueError, match="calibration.mtp must be"):
        RunConfig.from_dict({"deployment": {"model": "27B"},
                             "calibration": {"mtp": 0}}).validate()
    # DSv4-Flash's state is a fixed mixed-precision buffer, not a bf16 one
    assert M.MODELS["DSV4F"].state_fp32_ok is False
    with pytest.raises(ValueError, match="no bf16 recurrent state"):
        RunConfig.from_dict({"deployment": {"model": "DSV4F", "gpu": "H200",
                                            "tensor_parallel": 8,
                                            "recurrent_state_dtype": "fp32"}}).validate()


def test_explorer_emits_the_fractional_per_group_load():
    """A real download at 35B-A3B / 8xH200 / DP8 / 4 users — the page prices
    0.5 users per group and the file has to say 0.5, not 1."""
    p = Path(__file__).resolve().parent / "fixtures" / "explorer_dp8_fractional.toml"
    cfg = load_config(p)
    assert cfg.deployment.replicas == 8 and cfg.deployment.tensor_parallel == 1
    assert cfg.workload.users == 0.5
    cfg.validate()
    assert predict(cfg, n_iter=100).operating_point_users == 0.5


def test_fractional_per_group_load_is_preserved():
    """A DP8 deployment carrying 4 users runs half a user per group. That
    fraction IS the arrival rate, so rounding it to 1 doubles req/s and moves
    every queue figure with it."""
    dep = {"model": "35BA3B", "gpu": "H200", "tensor_parallel": 1, "replicas": 8}

    def at(u):
        return predict(RunConfig.from_dict({"deployment": dep,
                                            "workload": {"users": u}}), n_iter=100)

    half = at(0.5)                          # the page's 4 users across 8 groups
    assert half.operating_point_users == 0.5
    assert at(1).req_rate_main > 1.9 * half.req_rate_main
    # proportionality, read where the record's 4-decimal rounding is noise
    lo, hi = at(12.5), at(25)
    assert hi.req_rate_main == pytest.approx(2 * lo.req_rate_main, rel=1e-3)
    assert hi.prefill_duty == pytest.approx(2 * lo.prefill_duty, rel=1e-2)
    assert lo.operating_point_users == 12.5
    # the ladder is the place a load becomes a population, and only there
    from workingset.probe.ladder import build_ladder
    pops = build_ladder(half.predicted_limit_users, "0.5,1",
                        operating_point_users=half.operating_point_users)
    assert all(isinstance(p, int) and p >= 1 for p in pops)
    assert 1 in pops                        # 0.5 users -> one real session


def test_zero_users_still_drops_out_of_the_ladder():
    """`if operating_point_users:` must keep treating 0.0 as "no operating
    point", not add a rung for it."""
    from workingset.probe.ladder import build_ladder
    assert build_ladder(100.0, "1", operating_point_users=0.0) == [100]


def test_type_checked_at_the_boundary():
    with pytest.raises(ValueError, match="deployment.tensor_parallel"):
        RunConfig.from_dict({"deployment": {"tensor_parallel": "4"}})
    with pytest.raises(ValueError, match="workload.users"):
        RunConfig.from_dict({"workload": {"users": "12.5"}})
    with pytest.raises(ValueError, match="sub_shares_prefix"):
        RunConfig.from_dict({"workload": {"sub_shares_prefix": 1}})
    RunConfig.from_dict({"workload": {"think_time_s": 30}})   # int for a float is fine
    # users is a LOAD per replica group, so a fraction of one is legal
    assert RunConfig.from_dict({"workload": {"users": 12.5}}).workload.users == 12.5


def test_optional_float_is_type_checked_too():
    """`float | None` had no _SCALAR entry, so calibration.mtp was unchecked:
    a bool sailed through and a string reached the model as a TypeError three
    calls deep instead of a message at the file boundary."""
    with pytest.raises(ValueError, match="calibration.mtp"):
        RunConfig.from_dict({"calibration": {"mtp": True}})
    with pytest.raises(ValueError, match="calibration.mtp"):
        RunConfig.from_dict({"calibration": {"mtp": "1.7"}})
    # what it must still accept
    assert RunConfig.from_dict({"calibration": {"mtp": 1.7}}).calibration.mtp == 1.7
    assert RunConfig.from_dict({"calibration": {"mtp": 2}}).calibration.mtp == 2
    assert RunConfig.from_dict({"calibration": {"mtp": None}}).calibration.mtp is None


def test_predict_reference_row():
    """27B / 4xH200 TP4 / chunk 4096 at the measured workload: the explorer's
    reference example (the harness template's predictions block) — cache 403,
    latency 499, saturation 509, miss TTFT 0.92 s, B* 9.8. These are the
    explorer's per-pass-overhead convention; pinned so a convention drift
    (roofline vs explorer) fails here, not in a user's report."""
    cfg = RunConfig.from_dict({"deployment": {"model": "27B", "gpu": "H200",
                                              "tensor_parallel": 4,
                                              "max_num_batched_tokens": 4096}})
    p = predict(cfg, n_iter=300)
    assert p.binding_constraint == "decode"        # at the measured MBU 0.22
    assert 395 <= p.warm_capacity_p5 <= 411        # 403, Monte Carlo
    assert p.latency_ceiling_users == 499
    assert p.saturation_ceiling_users == 509
    assert abs(p.ttft_miss_s - 0.916) < 0.005
    assert abs(p.bstar_misses - 9.82) < 0.02
    assert p.predicted_limit_users == min(p.warm_capacity_p5, p.decode_ceiling_users,
                                          p.latency_ceiling_users,
                                          p.saturation_ceiling_users)
    assert 0 < p.prefill_duty < 1
    assert math.isfinite(p.ttft_miss_s) and p.ttft_miss_s > p.ttft_hit_s
    assert p.bstar_misses > 0
    assert p.replicas == 1


def test_predict_dp_system_multiplies():
    cfg = RunConfig.from_dict({"deployment": {"model": "35BA3B", "gpu": "H200",
                                              "tensor_parallel": 1, "replicas": 2}})
    p = predict(cfg, n_iter=200)
    assert p.replicas == 2
    assert p.system()["warm_capacity_p5"] == 2 * p.warm_capacity_p5


def test_predict_derives_headcount_load_per_dp_group():
    cfg = RunConfig.from_dict({
        "deployment": {"model": "35BA3B", "gpu": "H200", "replicas": 8},
        "workload": {"headcount": 40, "peak_active_share": 0.5,
                     "sessions_per_active_user": 2},
    })
    assert predict(cfg, n_iter=40).operating_point_users == 5


def test_predict_prints_headcount_conversion_and_people_ceilings(tmp_path, capsys):
    cfg = RunConfig.from_dict({
        "deployment": {"model": "35BA3B", "gpu": "H200", "replicas": 8},
        "workload": {"headcount": 2000, "peak_active_share": 0.35,
                     "sessions_per_active_user": 2.0},
    })
    p = tmp_path / "headcount.toml"
    p.write_text(cfg.dumps("toml"))
    assert cli.main(["predict", str(p), "--n-iter", "20"]) == 0
    out = capsys.readouterr().out
    assert "2,000 people x 0.35 active x 2.0 sessions = 1,400 sessions -> 175 /group on DP8" in out
    assert out.count(" people") == 5       # conversion plus all four ceilings


def test_predict_closed_uses_configured_think():
    base = {"deployment": {"model": "27B", "gpu": "H200", "tensor_parallel": 4}}
    fast = predict(RunConfig.from_dict({**base, "workload": {"think_time_s": 5.0}}),
                   closed=True, n_iter=100)
    slow = predict(RunConfig.from_dict({**base, "workload": {"think_time_s": 120.0}}),
                   closed=True, n_iter=100)
    assert fast.req_rate_main > 3 * slow.req_rate_main
    assert fast.saturation_ceiling_users < slow.saturation_ceiling_users


def test_predict_zero_users_and_json_safe():
    cfg = RunConfig.from_dict({"deployment": {"model": "27B", "gpu": "H200",
                                              "tensor_parallel": 4},
                               "workload": {"users": 0}})
    p = predict(cfg, n_iter=100)
    assert p.operating_point_users == 0 and p.req_rate_main == 0
    hot = RunConfig.from_dict({"deployment": {"model": "27B", "gpu": "H200",
                                              "tensor_parallel": 4},
                               "workload": {"users": 5000}})
    q = predict(hot, n_iter=100)
    assert q.prefill_duty >= 1 and not math.isfinite(q.ttft_miss_s)
    assert q.to_dict()["ttft_miss_s"] is None
    json.dumps(q.to_dict(), allow_nan=False)


def test_ram_offload_raises_cache_ceiling():
    base = {"deployment": {"model": "27B", "gpu": "H200", "tensor_parallel": 4}}
    dry = predict(RunConfig.from_dict(base), n_iter=200)
    ram = predict(RunConfig.from_dict({"deployment": {**base["deployment"],
                                                      "ram_gib": 512}}), n_iter=200)
    assert ram.cache_ceiling_users > dry.cache_ceiling_users


def test_init_default_filename_follows_the_format(tmp_path, monkeypatch, capsys):
    """`ws init --json` must not write JSON into a .toml the next command
    cannot parse: the default name follows --json, an explicit -o wins."""
    monkeypatch.chdir(tmp_path)
    assert cli.main(["init"]) == 0
    assert load_config(tmp_path / "workingset.toml") == RunConfig()
    assert not (tmp_path / "workingset.json").exists()

    assert cli.main(["init", "--json"]) == 0
    written = tmp_path / "workingset.json"
    assert json.loads(written.read_text())          # JSON, and parseable as it
    assert load_config(written) == RunConfig()

    assert cli.main(["init", "--json", "-o", "custom.cfg"]) == 0
    assert json.loads((tmp_path / "custom.cfg").read_text())

    capsys.readouterr()
    assert cli.main(["init", "--json", "-o", "-"]) == 0
    assert json.loads(capsys.readouterr().out)      # stdout, no file written
