#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "httpx>=0.27",
# ]
# ///
"""
Live-endpoint validation harness for the serving-capacity model
(scripts/scenario_model.py; interactive/index.html mirrors it in JS).

The model predicts four ceilings for a configuration — cache (warm p5),
decode (users at the tok/s floor), latency (users where a miss's mean TTFT
hits the budget) and saturation (prefill duty 100%) — and the binding one
is the smallest. Every one of those is a projection: docs/scenarios.md
("Planning stance") is explicit that the study is a hypothesis generator
and that "comfortable capacity" is DEFINED as measured SLO capacity, a
number the model cannot produce. This script is that measurement: it
drives a LIVE vLLM endpoint with the closed-loop workload the model
assumes and finds the real limit.

  MEASURED SLO CAPACITY := the largest simulated population meeting
      p{percentile} TTFT <= ttft_budget_s
      AND per-user p50 decode >= itl_floor_tok_s
  over a geometric load ladder bracketing the model's predicted limit.

Workload (one simulated user = one session, assumption 1 of the planner):
every session shares ONE byte-identical system prefix (so vLLM prefix
caching engages), carries a per-session context drawn from the model's
log-normal (median/sigma; tokens ~ chars/4, and the ACHIEVED prompt_tokens
are read back from `usage` and reported against the intent), and loops:
think (exponential, mean think_time_s) -> send prior context + a
warm_turn_tokens turn -> stream the response. With probability miss_rate a
turn prepends a random salt, making the whole request unmatchable — the
model's cache miss. Subagent sessions (ratio r, leaner prompts) run the
same loop with their OWN byte-stable prefix (subagent_prefix_tokens),
exactly as Workload prices them — unless sub_shares_prefix points both
classes at the single user prefix.

What one run establishes, and what it cannot: the ladder separates the
ceilings only by their observed failure mode (TTFT breach vs decode-floor
breach); warm capacity is bounded BELOW unless the run reaches eviction;
correlated-flush tolerance (B*) needs --burst. The verdict table names
which is which — read the "what this run does not establish" trailer
before quoting any number from it.

Usage:
    uv run validate_deployment.py --dry-run        # offline: plan + sampler self-check
    uv run validate_deployment.py --base-url http://host:8000/v1
    uv run validate_deployment.py --burst 8        # B* probe instead of the ladder

Ctrl-C at any point prints a partial report over the rungs completed.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import math
import os
import random
import sys
import time
from dataclasses import dataclass, field

# --- BEGIN CONFIG (generated by the interactive explorer) ---
CONFIG = {
    # Reference example: 27B / 4xH200 TP4, f = 1%, max_num_batched_tokens 4096.
    # The explorer replaces this whole block with the configuration on screen.
    "endpoint": {
        "base_url": "http://localhost:8000/v1",
        "model": "Qwen/Qwen3.6-27B-FP8",
        "api_key_env": "VLLM_API_KEY",       # env var NAME, not the key itself
    },
    "workload": {
        "system_prefix_tokens": 15_000,      # shared prefix, identical bytes for all sessions
        "user_prompt_median_tokens": 31_000, # log-normal median of a user session's context
        "user_prompt_sigma": 0.81,           # log-normal shape (sigma of ln L)
        "warm_turn_tokens": 2_000,           # new tokens appended per warm turn
        "think_time_s": 30.0,                # mean turn-to-turn interval (exponential)
        "subagent_ratio": 0.10,              # subagent sessions per user session
        "subagent_median_tokens": 8_000,
        "subagent_sigma": 0.9,
        "subagent_prefix_tokens": 3_000,     # subagents' own lean shared prefix
        "sub_shares_prefix": False,          # True = subagents reuse the user prefix
        "miss_rate": 0.01,                   # per-turn probability of a forced full re-prefill
        "max_output_tokens": 1_000,          # decoded tokens per turn (OUT_TOKENS_DEFAULT)
    },
    "slo": {
        "ttft_budget_s": 10.0,
        "itl_floor_tok_s": 40,               # the study's hard per-user decode floor
        "percentile": 95,                    # TTFT percentile the SLO is read at
    },
    "predictions": {
        "warm_capacity_p5": 403,             # user-class warm sessions, p5 (plan column)
        "decode_ceiling_users": 428,         # users at the 40 tok/s p50 floor (mns@40)
        "latency_ceiling_users": 499,        # users where a miss's mean TTFT = budget
        "saturation_ceiling_users": 509,     # users where prefill duty = 100%
        "binding_constraint": "cache",       # argmin of the four ceilings
        "predicted_limit_users": 403,        # the binding ceiling's value
        "operating_point_users": 64,         # the load ttft_miss_s / bstar were computed AT
        "ttft_miss_s": 0.92,                 # mean TTFT of a miss at the operating point
        "bstar_misses": 9.8,                 # B*: simultaneous misses drained inside the budget
        # H9 (PR #37): the decode batch the LOAD produces, not the all-warm
        # stress point. Arrivals are open-loop, so most of the warm pool is
        # idle between turns and the batch is far smaller / far faster.
        "steady_decode_seqs": 3.11,          # sequences decoding at the operating point
        "steady_decode_tok_s": 756,          # per-user decode at THAT batch size
        # the chunk-size hypothesis. Both are per-SSE-event gaps, ms.
        "itl_normal_ms": 2.2,                # gap with no prefill in the pass
        "itl_worst_freeze_ms": 171,          # last chunk of a 180k cold re-prefill
    },
    "hypotheses": [
        "H-cache: >= 403 user sessions stay warm (p5). This run bounds it below "
        "unless load reaches eviction (watch the effective-cold fraction).",
        "H-decode: per-user p50 decode holds >= 40 tok/s up to ~428 concurrent users.",
        "H-latency: a cache miss's mean TTFT reaches the 10 s budget near ~499 users.",
        "H-saturation: prefill duty reaches 100% near ~509 users; above it the queue "
        "has no steady state.",
        "H-binding: the binding constraint is 'cache' — measured SLO capacity should "
        "land near 403 users.",
        "H-ttft-miss: a forced miss's mean TTFT at the operating point is ~0.92 s.",
        "H-burst (needs --burst): a simultaneous flush of <= 9 misses (B* = 9.8) "
        "drains inside the TTFT budget; a larger one does not.",
        # --- the two the reference CONFIG never carried ----------------------
        "H-steady (H9): at the operating point the decode batch holds ~3.1 "
        "sequences at ~756 tok/s each — NOT the whole warm pool at the stress "
        "figure. Read against the measured concurrent-decode count, not the "
        "population.",
        "H-itl-spike: the normal inter-token gap is ~2.2 ms and the worst freeze "
        "behind one chunk of a 180k cold re-prefill is ~171 ms at "
        "max_num_batched_tokens=4096 (~1,289 ms at 32,768). This is the "
        "chunk-size claim: the MEAN barely moves between the two settings, so "
        "it must be read on the INTER-TOKEN GAPS table, never on decode p50.",
    ],
}
# --- END CONFIG ---

DEFAULT_RUNGS = "0.25,0.5,0.75,1,1.25,1.5,2"


# ============================================================================
# small numerics (no numpy: this file must run standalone from a download)
# ============================================================================
def pct(xs, q: float) -> float:
    """Linear-interpolation percentile; nan on empty input."""
    if not xs:
        return float("nan")
    s = sorted(xs)
    if len(s) == 1:
        return float(s[0])
    pos = (len(s) - 1) * q / 100.0
    lo = math.floor(pos)
    frac = pos - lo
    hi = min(lo + 1, len(s) - 1)
    return float(s[lo] * (1 - frac) + s[hi] * frac)


def fmt(x, unit: str = "", nd: int = 2) -> str:
    if x is None or (isinstance(x, float) and not math.isfinite(x)):
        return "-"
    return f"{x:.{nd}f}{unit}"


# ============================================================================
# synthetic text  (tokens ~ chars / chars_per_token; the run reads back the
# ACHIEVED prompt_tokens from `usage` and reports the ratio, closing the loop)
# ============================================================================
_VOCAB = ("the build failed on stage three because a header moved and the cache "
          "key did not include it so the runner reused a stale object then the "
          "linker saw two symbols with one name and gave up while the test "
          "suite kept polling a socket that nothing owned anymore").split()


def make_text(rng: random.Random, tokens: float, cpt: float) -> str:
    """~`tokens` worth of plain prose (cpt chars per token, measured later)."""
    budget = max(int(tokens * cpt), 1)
    out, n = [], 0
    while n < budget:
        w = _VOCAB[rng.randrange(len(_VOCAB))]
        out.append(w)
        n += len(w) + 1
    return " ".join(out)[:budget]


def draw_session_tokens(rng: random.Random, median: float, sigma: float,
                        prefix: float, cap: float) -> int:
    """One session's full prompt length: log-normal(median, sigma), clipped to
    [prefix, cap] exactly as Workload.sample clips (a prompt always contains
    at least its shared prefix, never more than the cap)."""
    full = rng.lognormvariate(math.log(median), sigma)
    return int(min(max(full, prefix), cap))


# ============================================================================
# measurement records
# ============================================================================
@dataclass
class Turn:
    uid: int
    is_sub: bool
    kind: str                 # "first" (session establishment) | "hit" | "miss"
    t_start: float
    ttft: float | None = None
    decode_tps: float | None = None
    ptok_intended: int = 0
    ptok_achieved: int | None = None
    ctok: int | None = None
    error: str | None = None
    # --- inter-token gap stats (the ITL-spike evidence) ---------------------
    # decode_tps above is a MEAN over the whole stream and is nearly blind to a
    # freeze: a single 1.3 s stall inside a 1,000-token response otherwise
    # running at 200 tok/s reads as ~159 tok/s — a 20% dip standing in for a
    # 260x spike. These fields keep the distribution the mean throws away.
    # Gaps are measured per SSE EVENT, not per token; chunk_tok_ratio in the
    # report says how far apart those two are on this endpoint.
    itl_p50: float | None = None      # s, median gap within this response
    itl_max: float | None = None      # s, worst gap within this response
    n_gaps: int = 0
    n_freeze: int = 0                 # gaps >= the freeze threshold
    stall_s: float = 0.0              # total time inside those gaps
    span_s: float | None = None       # t_last - t_first
    n_chunks: int = 0


@dataclass
class RungResult:
    pop: int                  # user-class sessions (the population axis)
    n_sub: int
    n_turns: int = 0
    n_hit: int = 0
    n_miss: int = 0
    n_err: int = 0
    ttft_hit_p50: float = float("nan")
    ttft_hit_pX: float = float("nan")
    ttft_miss_p50: float = float("nan")
    ttft_miss_pX: float = float("nan")
    ttft_miss_mean: float = float("nan")
    ttft_all_pX: float = float("nan")
    decode_p50: float = float("nan")
    # --- ITL gap distribution (see Turn) ---
    itl_p50_ms: float = float("nan")        # the normal inter-token gap
    itl_worst_p50_ms: float = float("nan")  # typical worst freeze, per response
    itl_worst_p95_ms: float = float("nan")  # unlucky response's worst freeze
    itl_max_ms: float = float("nan")        # worst freeze seen anywhere
    freeze_per_ktok: float = float("nan")   # gaps >= threshold per 1k tokens
    stall_frac: float = float("nan")        # share of decode time inside them
    chunk_tok_ratio: float = float("nan")   # tokens per SSE event (1.0 = per-token)
    achieved_rps: float = float("nan")
    offered_rps: float = float("nan")
    evict_frac: float = float("nan")   # hit-intended turns that look cold (heuristic)
    ptok_ratio: float = float("nan")   # achieved / intended prompt tokens, median
    passed: bool = False
    reasons: list = field(default_factory=list)
    blown: bool = False                # SLOs clearly blown -> ladder stops here
    partial: bool = False              # interrupted mid-window: shown, never counted


# ============================================================================
# one streamed request against the OpenAI-compatible /v1/completions
# ============================================================================
async def send_turn(client, args, cfg, prompt: str, turn: Turn) -> str:
    """Stream one completion; fills `turn` in place, returns the response text
    (appended to the session so the next warm turn extends the cached run)."""
    ep = cfg["endpoint"]
    payload = {
        "model": args.model or ep["model"],
        "prompt": prompt,
        "max_tokens": cfg["workload"]["max_output_tokens"],
        "temperature": 0.7,
        "stream": True,
        "stream_options": {"include_usage": True},
    }
    if not args.no_ignore_eos:
        # vLLM extension: guarantees max_output_tokens of decode per turn, so
        # decode tok/s is measured over a fixed-length stream, not over
        # whatever an early EOS leaves. Strict non-vLLM endpoints: disable.
        payload["ignore_eos"] = True
    headers = {}
    key = os.environ.get(args.api_key_env or ep["api_key_env"] or "", "")
    if key:
        headers["Authorization"] = f"Bearer {key}"

    base = (args.base_url or ep["base_url"]).rstrip("/")
    t0 = time.monotonic()
    t_first = t_last = None
    n_chunks, text, usage = 0, [], None
    gaps: list[float] = []
    try:
        async with client.stream("POST", f"{base}/completions", json=payload,
                                 headers=headers,
                                 timeout=args.request_timeout_s) as r:
            r.raise_for_status()
            async for line in r.aiter_lines():
                if not line.startswith("data:"):
                    continue
                data = line[5:].strip()
                if data == "[DONE]":
                    break
                obj = json.loads(data)
                if obj.get("usage"):
                    usage = obj["usage"]
                ch = obj.get("choices") or []
                if ch and ch[0].get("text"):
                    now = time.monotonic()
                    if t_first is None:
                        t_first = now
                        turn.ttft = now - t0
                    else:
                        gaps.append(now - t_last)
                    t_last = now
                    n_chunks += 1
                    text.append(ch[0]["text"])
    except asyncio.CancelledError:
        raise
    except Exception as e:  # connection, HTTP status, timeout, bad JSON
        turn.error = f"{type(e).__name__}: {e}"[:200]
        return ""

    if usage:
        turn.ptok_achieved = usage.get("prompt_tokens")
        turn.ctok = usage.get("completion_tokens")
    n_tok = turn.ctok if turn.ctok else n_chunks
    if t_first is not None and t_last is not None and t_last > t_first and n_tok > 1:
        turn.decode_tps = (n_tok - 1) / (t_last - t_first)
        turn.span_s = t_last - t_first
    turn.n_chunks = n_chunks
    if gaps:
        freeze_s = args.freeze_threshold_ms / 1e3
        big = [g for g in gaps if g >= freeze_s]
        turn.itl_p50 = pct(gaps, 50)
        turn.itl_max = max(gaps)
        turn.n_gaps = len(gaps)
        turn.n_freeze = len(big)
        turn.stall_s = sum(big)
    return "".join(text)


# ============================================================================
# closed-loop session
# ============================================================================
async def user_loop(client, args, cfg, uid: int, is_sub: bool,
                    system_prefix: str, sub_prefix: str, turns: list,
                    stop: asyncio.Event, stagger_s: float):
    wl = cfg["workload"]
    rng = random.Random((args.seed << 20) ^ uid)
    cpt = args.chars_per_token
    median = wl["subagent_median_tokens"] if is_sub else wl["user_prompt_median_tokens"]
    sigma = wl["subagent_sigma"] if is_sub else wl["user_prompt_sigma"]
    # each request class carries ITS OWN byte-stable prefix, exactly as
    # Workload.sample prices it: subagents get the lean sub prefix unless
    # sub_shares_prefix points them at the user prefix (the old behaviour
    # — always the user prefix — silently tested a ~3x lighter subagent
    # workload than the one the predictions were computed on)
    own_sub = is_sub and not wl.get("sub_shares_prefix", False)
    prefix_tok = wl.get("subagent_prefix_tokens", 3_000) if own_sub \
        else wl["system_prefix_tokens"]
    prefix_txt = sub_prefix if own_sub else system_prefix
    full = draw_session_tokens(rng, median, sigma, prefix_tok,
                               args.context_cap_tokens)
    # per-session unique context on top of this class's shared prefix
    ctx = make_text(rng, max(full - prefix_tok, 0), cpt)
    history = ""
    n_turn = 0
    cap = args.turns_per_user or math.inf

    await asyncio.sleep(stagger_s)          # spread session establishment over the ramp
    while not stop.is_set() and n_turn < cap:
        first = n_turn == 0
        if not first:
            # exponential think time; wake early if the rung ends
            try:
                await asyncio.wait_for(stop.wait(),
                                       rng.expovariate(1.0 / wl["think_time_s"]))
                break
            except asyncio.TimeoutError:
                pass
        is_miss = (not first) and rng.random() < wl["miss_rate"]
        # a salt ahead of the prefix makes the WHOLE request unmatchable — the
        # model's cache miss (full re-prefill), applied to this turn only
        salt = f"[miss-salt {rng.getrandbits(64):016x}] " if is_miss else ""
        turn_text = "" if first else "\n" + make_text(rng, wl["warm_turn_tokens"], cpt)
        prompt = salt + prefix_txt + "\n" + ctx + history + turn_text
        turn = Turn(uid=uid, is_sub=is_sub,
                    kind="first" if first else ("miss" if is_miss else "hit"),
                    t_start=time.monotonic(),
                    ptok_intended=int(len(prompt) / cpt))
        turns.append(turn)
        reply = await send_turn(client, args, cfg, prompt, turn)
        # the response joins the context: the next warm turn extends the cached
        # sequence exactly the way a real agentic session does
        history += turn_text + reply
        n_turn += 1


# ============================================================================
# one ladder rung
# ============================================================================
def eval_rung(pop: int, n_sub: int, turns: list, measure_start: float,
              cfg, args) -> RungResult:
    slo, wl = cfg["slo"], cfg["workload"]
    p = slo["percentile"]
    res = RungResult(pop=pop, n_sub=n_sub)

    measured = [t for t in turns
                if t.t_start >= measure_start and t.kind in ("hit", "miss")]
    res.n_err = sum(1 for t in measured if t.error)
    ok = [t for t in measured if not t.error and t.ttft is not None]
    hit = [t for t in ok if t.kind == "hit"]
    miss = [t for t in ok if t.kind == "miss"]
    res.n_turns, res.n_hit, res.n_miss = len(ok), len(hit), len(miss)

    res.ttft_hit_p50 = pct([t.ttft for t in hit], 50)
    res.ttft_hit_pX = pct([t.ttft for t in hit], p)
    res.ttft_miss_p50 = pct([t.ttft for t in miss], 50)
    res.ttft_miss_pX = pct([t.ttft for t in miss], p)
    if miss:
        res.ttft_miss_mean = sum(t.ttft for t in miss) / len(miss)
    res.ttft_all_pX = pct([t.ttft for t in ok], p)

    # per-user decode: median within each user, then p50 across users — the
    # model's "per-user p50" is a population statistic, not a turn statistic
    by_user: dict[int, list] = {}
    for t in ok:
        if t.decode_tps is not None:
            by_user.setdefault(t.uid, []).append(t.decode_tps)
    res.decode_p50 = pct([pct(v, 50) for v in by_user.values()], 50)

    # ITL gap distribution. decode_p50 above answers "how fast on average";
    # these answer "what did it feel like" — the chunk-size hypothesis lives
    # entirely here, because chunking moves the tail and leaves the mean flat.
    g = [t for t in ok if t.n_gaps > 0]
    if g:
        res.itl_p50_ms = pct([t.itl_p50 for t in g], 50) * 1e3
        worst = [t.itl_max for t in g]
        res.itl_worst_p50_ms = pct(worst, 50) * 1e3
        res.itl_worst_p95_ms = pct(worst, 95) * 1e3
        res.itl_max_ms = max(worst) * 1e3
        n_gaps = sum(t.n_gaps for t in g)
        if n_gaps:
            res.freeze_per_ktok = 1e3 * sum(t.n_freeze for t in g) / n_gaps
        span = sum(t.span_s for t in g if t.span_s)
        if span > 0:
            res.stall_frac = sum(t.stall_s for t in g) / span
        chunks = sum(t.n_chunks for t in g)
        ctoks = sum(t.ctok for t in g if t.ctok)
        if chunks and ctoks:
            res.chunk_tok_ratio = ctoks / chunks

    res.achieved_rps = len(measured) / args.measure_s
    res.offered_rps = (pop + n_sub) / wl["think_time_s"]

    # eviction heuristic (the baseline's warm/cold classifier): a hit-intended
    # turn whose TTFT is >= 0.4x the median forced-miss TTFT re-prefilled — its
    # cached run was evicted. A heuristic, flagged as such in the report.
    if hit and miss and math.isfinite(res.ttft_miss_p50):
        thresh = 0.4 * res.ttft_miss_p50
        res.evict_frac = sum(1 for t in hit if t.ttft >= thresh) / len(hit)

    ratios = [t.ptok_achieved / t.ptok_intended for t in ok
              if t.ptok_achieved and t.ptok_intended]
    res.ptok_ratio = pct(ratios, 50)

    # SLO verdict for this rung
    budget, floor = slo["ttft_budget_s"], slo["itl_floor_tok_s"]
    err_frac = res.n_err / max(len(measured), 1)
    if not ok:
        res.reasons.append("no successful turns in the measure window")
        res.blown = True
    else:
        if err_frac > 0.05:
            res.reasons.append(f"error rate {err_frac:.0%}")
        if res.ttft_all_pX > budget:
            res.reasons.append(f"p{p} TTFT {res.ttft_all_pX:.2f}s > {budget:g}s")
        if math.isfinite(res.decode_p50) and res.decode_p50 < floor:
            res.reasons.append(f"decode p50 {res.decode_p50:.1f} < {floor:g} tok/s")
        res.blown = (res.ttft_all_pX > 2 * budget
                     or (math.isfinite(res.decode_p50)
                         and res.decode_p50 < 0.5 * floor)
                     or err_frac > 0.20)
    res.passed = not res.reasons
    return res


async def run_rung(client, args, cfg, pop: int, state: dict) -> RungResult:
    wl = cfg["workload"]
    n_sub = round(pop * wl["subagent_ratio"])
    turns: list[Turn] = []
    state["current"] = (pop, n_sub, turns, None)
    stop = asyncio.Event()
    system_prefix = state["system_prefix"]

    tasks = []
    rng = random.Random(args.seed ^ pop)
    for i in range(pop + n_sub):
        tasks.append(asyncio.create_task(user_loop(
            client, args, cfg, uid=pop * 100_000 + i, is_sub=(i >= pop),
            system_prefix=system_prefix, sub_prefix=state["sub_prefix"],
            turns=turns, stop=stop,
            stagger_s=rng.uniform(0, max(args.ramp_s, 1.0)))))
    t0 = time.monotonic()
    measure_start = t0 + args.ramp_s
    state["current"] = (pop, n_sub, turns, measure_start)
    try:
        await asyncio.sleep(args.ramp_s + args.measure_s)
    finally:
        stop.set()
        for t in tasks:
            t.cancel()
        await asyncio.gather(*tasks, return_exceptions=True)

    res = eval_rung(pop, n_sub, turns, measure_start, cfg, args)
    state["rungs"].append(res)
    state["current"] = None
    return res


# ============================================================================
# burst probe  (--burst N: validates B*, the correlated-flush tolerance)
# ============================================================================
async def run_burst(client, args, cfg, state: dict):
    """From steady standing load, fire N simultaneous forced misses and time
    the drain. B* predicts the largest N whose LAST first-token still lands
    inside the TTFT budget (spike_tolerance in scenario_model.py)."""
    wl = cfg["workload"]
    pred = cfg["predictions"]
    # standing load defaults to the OPERATING POINT the B* prediction was
    # computed at (old default 0.5 x limit drained the burst into a
    # different duty cycle than the one that priced it)
    pop = args.burst_users or max(1, round(
        pred.get("operating_point_users")
        or 0.5 * pred["predicted_limit_users"]))
    n_sub = round(pop * wl["subagent_ratio"])
    n = args.burst
    print(f"\nBURST PROBE: standing load {pop} users (+{n_sub} subagents), "
          f"ramp {args.ramp_s:g}s, then {n} simultaneous forced misses "
          f"(predicted B* = {pred['bstar_misses']:g})")

    turns: list[Turn] = []
    stop = asyncio.Event()
    rng = random.Random(args.seed ^ 0xB0057)
    tasks = [asyncio.create_task(user_loop(
        client, args, cfg, uid=900_000 + i, is_sub=(i >= pop),
        system_prefix=state["system_prefix"], sub_prefix=state["sub_prefix"],
        turns=turns, stop=stop,
        stagger_s=rng.uniform(0, max(args.ramp_s, 1.0))))
        for i in range(pop + n_sub)]
    try:
        await asyncio.sleep(args.ramp_s)

        async def one_miss(i: int) -> Turn:
            r = random.Random((args.seed << 8) ^ (0xF00D + i))
            full = draw_session_tokens(r, wl["user_prompt_median_tokens"],
                                       wl["user_prompt_sigma"],
                                       wl["system_prefix_tokens"],
                                       args.context_cap_tokens)
            salt = f"[miss-salt {r.getrandbits(64):016x}] "
            prompt = (salt + state["system_prefix"] + "\n"
                      + make_text(r, max(full - wl["system_prefix_tokens"], 0),
                                  args.chars_per_token))
            t = Turn(uid=990_000 + i, is_sub=False, kind="miss",
                     t_start=time.monotonic(),
                     ptok_intended=int(len(prompt) / args.chars_per_token))
            await send_turn(client, args, cfg, prompt, t)
            return t

        t_fire = time.monotonic()
        burst_turns = await asyncio.gather(*[one_miss(i) for i in range(n)])
    finally:
        stop.set()
        for t in tasks:
            t.cancel()
        await asyncio.gather(*tasks, return_exceptions=True)

    ok = [t for t in burst_turns if t.ttft is not None and not t.error]
    result = {
        "n": n, "standing_users": pop,
        "n_ok": len(ok), "n_err": n - len(ok),
        # drain: fire -> the LAST request's first token (all fired together,
        # so last first-token = the fluid model's T_drain, whatever the
        # scheduler's discipline — see burst_drain_seconds)
        "drain_s": (max(t.t_start + t.ttft for t in ok) - t_fire) if ok else None,
        "last_ttft_s": max((t.ttft for t in ok), default=None),
        "ttft_p50_s": pct([t.ttft for t in ok], 50),
    }

    # What the STANDING load felt while the burst was draining. This is the
    # chunk-size hypothesis in its purest form: the burst is a controlled
    # cold-prefill event, and these are the decoders it lands on. Only turns
    # still streaming at fire time can have been hit by it.
    victims = [t for t in turns
               if t.n_gaps > 0 and t.span_s
               and t.t_start <= t_fire <= t.t_start + (t.ttft or 0) + t.span_s]
    if victims:
        worst = [t.itl_max for t in victims]
        result["standing_n"] = len(victims)
        result["standing_itl_p50_ms"] = pct([t.itl_p50 for t in victims], 50) * 1e3
        result["standing_worst_p50_ms"] = pct(worst, 50) * 1e3
        result["standing_worst_max_ms"] = max(worst) * 1e3
        n_gaps = sum(t.n_gaps for t in victims)
        result["standing_freeze_per_ktok"] = (
            1e3 * sum(t.n_freeze for t in victims) / n_gaps) if n_gaps else None

    state["burst"] = result
    print(f"  burst: {len(ok)}/{n} answered | TTFT p50 {fmt(result['ttft_p50_s'], 's')} "
          f"| last first-token {fmt(result['last_ttft_s'], 's')} "
          f"| drain {fmt(result['drain_s'], 's')}")
    if victims:
        print(f"  standing load hit by it: {len(victims)} responses in flight | "
              f"normal gap {fmt(result['standing_itl_p50_ms'], ' ms', 1)} | "
              f"worst gap p50 {fmt(result['standing_worst_p50_ms'], ' ms', 0)} | "
              f"worst seen {fmt(result['standing_worst_max_ms'], ' ms', 0)}")


# ============================================================================
# verdicts
# ============================================================================
CHECK, CROSS, TILDE = "✓", "✗", "~"


def bracket_verdict(pred: float, lo: float | None, hi: float | None) -> tuple:
    """Compare a predicted ceiling against the measured (largest-pass,
    smallest-fail] population bracket. lo/hi None = side not observed.
    ~ means within 25% of the nearest observed edge."""
    if pred is None:
        return TILDE, "no prediction"
    if lo is None and hi is None:
        return TILDE, "no data"
    if hi is None:                       # never failed: lower bound only
        if pred >= lo:
            return TILDE, f"not reached (measured >= {lo:g}, predicted {pred:g})"
        if lo <= 1.25 * pred:
            return TILDE, f"measured >= {lo:g}, within 25% above prediction"
        return CROSS, f"passed at {lo:g} > 1.25x predicted {pred:g} (model conservative)"
    if lo is None:                       # every rung failed: upper bound only
        if pred <= hi:
            return TILDE, f"capacity < {hi:g}; prediction {pred:g} not excluded"
        if pred <= hi / 0.75:
            return TILDE, f"capacity < {hi:g}, within 25% below prediction"
        return CROSS, f"failed at {hi:g} < 0.75x predicted {pred:g} (model optimistic)"
    if lo <= pred <= hi:
        return CHECK, f"predicted {pred:g} inside measured ({lo:g}, {hi:g}]"
    edge = lo if pred < lo else hi
    if 0.75 <= pred / edge <= 1.25:
        return TILDE, f"predicted {pred:g} within 25% of measured ({lo:g}, {hi:g}]"
    return CROSS, f"predicted {pred:g} outside measured ({lo:g}, {hi:g}]"


def print_report(state: dict, cfg, args, interrupted: bool = False):
    slo, pred = cfg["slo"], cfg["predictions"]
    p = slo["percentile"]
    rungs: list[RungResult] = list(state["rungs"])
    # a partially-measured current rung still carries information on Ctrl-C
    if interrupted and state.get("current"):
        pop, n_sub, turns, ms = state["current"]
        if ms is not None and any(t.t_start >= ms for t in turns):
            r = eval_rung(pop, n_sub, turns, ms, cfg, args)
            r.partial = True           # shown for orientation, excluded from verdicts
            rungs.append(r)

    print("\n" + "=" * 78)
    print("VALIDATION REPORT" + ("  [INTERRUPTED — partial]" if interrupted else ""))
    print("=" * 78)

    if rungs:
        print(f"\n{'users':>6} {'turns':>6} {'hit':>5} {'miss':>5} {'err':>4} "
              f"{'TTFT hit p50/p' + str(p):>17} {'TTFT miss p50/p' + str(p):>18} "
              f"{'dec p50':>8} {'req/s':>6} {'verdict'}")
        for r in rungs:
            verdict = "PASS" if r.passed else "FAIL: " + "; ".join(r.reasons)
            if r.partial:
                verdict += " [partial — not counted]"
            print(f"{r.pop:>6} {r.n_turns:>6} {r.n_hit:>5} {r.n_miss:>5} "
                  f"{r.n_err:>4} "
                  f"{fmt(r.ttft_hit_p50, '', 2):>8}/{fmt(r.ttft_hit_pX, 's', 2):<8} "
                  f"{fmt(r.ttft_miss_p50, '', 2):>8}/{fmt(r.ttft_miss_pX, 's', 2):<9} "
                  f"{fmt(r.decode_p50, '', 1):>8} {fmt(r.achieved_rps, '', 2):>6} "
                  f"{verdict}")
        # ---- ITL gap table: what the chunk size actually moves -------------
        if any(math.isfinite(r.itl_p50_ms) for r in rungs):
            thr = args.freeze_threshold_ms
            print(f"\nINTER-TOKEN GAPS (freeze = a gap >= {thr:g} ms)")
            print(f"{'users':>6} {'normal p50':>11} {'worst/resp p50':>15} "
                  f"{'worst/resp p95':>15} {'worst seen':>11} "
                  f"{'freezes/ktok':>13} {'time stalled':>13}")
            for r in rungs:
                print(f"{r.pop:>6} {fmt(r.itl_p50_ms, ' ms', 1):>11} "
                      f"{fmt(r.itl_worst_p50_ms, ' ms', 0):>15} "
                      f"{fmt(r.itl_worst_p95_ms, ' ms', 0):>15} "
                      f"{fmt(r.itl_max_ms, ' ms', 0):>11} "
                      f"{fmt(r.freeze_per_ktok, '', 1):>13} "
                      f"{fmt(r.stall_frac * 100 if math.isfinite(r.stall_frac) else float('nan'), '%', 1):>13}")
            cr = [r.chunk_tok_ratio for r in rungs
                  if math.isfinite(r.chunk_tok_ratio)]
            if cr and abs(pct(cr, 50) - 1.0) > 0.05:
                print(f"  NOTE: {pct(cr, 50):.2f} tokens per SSE event — gaps are "
                      "per event, so per-token gaps are finer than shown.")

        ratios = [r.ptok_ratio for r in rungs if math.isfinite(r.ptok_ratio)]
        if ratios:
            med = pct(ratios, 50)
            print(f"\nachieved/intended prompt tokens (median): {med:.2f} "
                  f"(tokens ~ chars/{args.chars_per_token:g}; if far from 1.0, "
                  f"re-run with --chars-per-token {args.chars_per_token / med:.1f})")

    # measured SLO capacity bracket — full windows only; a partial rung is
    # orientation, not evidence
    rungs = [r for r in rungs if not r.partial]
    passes = [r.pop for r in rungs if r.passed]
    fails = [r.pop for r in rungs if not r.passed]
    lo = max(passes) if passes else None
    hi = min(fails) if fails else None
    print("\nMEASURED SLO CAPACITY "
          f"(p{p} TTFT <= {slo['ttft_budget_s']:g}s AND per-user p50 decode "
          f">= {slo['itl_floor_tok_s']:g} tok/s):")
    if lo is not None and hi is not None:
        print(f"  in ({lo}, {hi}] — largest passing population {lo} users")
    elif lo is not None:
        print(f"  >= {lo} users (no failing rung observed — a lower bound)")
    elif hi is not None:
        print(f"  < {hi} users (no passing rung observed)")
    else:
        print("  not measured")

    # failure-mode split: which ceilings did the ladder actually see?
    ttft_fails = [r.pop for r in rungs
                  if any("TTFT" in s for s in r.reasons)]
    dec_fails = [r.pop for r in rungs
                 if any("decode" in s for s in r.reasons)]
    lat_lo = max((r.pop for r in rungs
                  if r.passed or not any("TTFT" in s for s in r.reasons)),
                 default=None)
    dec_lo = max((r.pop for r in rungs
                  if r.passed or not any("decode" in s for s in r.reasons)),
                 default=None)

    print("\nPREDICTED vs MEASURED")
    print(f"{'quantity':<28} {'predicted':>10} {'measured':>22}  verdict")

    def row(name, predicted, measured, verdict, note):
        print(f"{name:<28} {predicted:>10} {measured:>22}  {verdict}  {note}")

    # binding limit
    v, note = bracket_verdict(pred.get("predicted_limit_users"), lo, hi)
    row(f"SLO capacity ({pred.get('binding_constraint', '?')} binds)",
        f"{pred.get('predicted_limit_users', '-')}",
        (f"({lo},{hi}]" if lo is not None and hi is not None
         else f">={lo}" if lo is not None else f"<{hi}" if hi is not None else "-"),
        v, note)

    # latency ceiling: separable only if a rung failed on TTFT
    if ttft_fails:
        v, note = bracket_verdict(pred.get("latency_ceiling_users"),
                                  lat_lo, min(ttft_fails))
        row("latency ceiling", f"{pred.get('latency_ceiling_users', '-')}",
            f"({lat_lo},{min(ttft_fails)}]", v, note)
    else:
        row("latency ceiling", f"{pred.get('latency_ceiling_users', '-')}",
            "not separable", TILDE, "no TTFT-mode failure observed")

    # decode ceiling: separable only if a rung failed on the floor
    if dec_fails:
        v, note = bracket_verdict(pred.get("decode_ceiling_users"),
                                  dec_lo, min(dec_fails))
        row("decode ceiling", f"{pred.get('decode_ceiling_users', '-')}",
            f"({dec_lo},{min(dec_fails)}]", v, note)
    else:
        row("decode ceiling", f"{pred.get('decode_ceiling_users', '-')}",
            "not separable", TILDE, "no decode-floor failure observed")

    # saturation: visible as achieved req/s falling well under the offered rate
    sat_evidence = [r for r in rungs if not r.passed and r.n_turns > 0
                    and math.isfinite(r.achieved_rps)
                    and r.achieved_rps < 0.7 * r.offered_rps]
    if sat_evidence:
        r0 = min(sat_evidence, key=lambda r: r.pop)
        row("saturation ceiling", f"{pred.get('saturation_ceiling_users', '-')}",
            f"<= {r0.pop}", TILDE,
            f"achieved {r0.achieved_rps:.2f} req/s vs offered "
            f"{r0.offered_rps:.2f} — throughput plateau")
    else:
        row("saturation ceiling", f"{pred.get('saturation_ceiling_users', '-')}",
            "not separable", TILDE,
            "closed loop throttles before duty=100% is visible")

    # warm capacity: bounded below by the largest population whose hit turns
    # stayed warm (low effective-cold fraction), never bounded above here
    held = [r.pop for r in rungs if r.n_hit > 0
            and (not math.isfinite(r.evict_frac) or r.evict_frac < 0.05)]
    wc = pred.get("warm_capacity_p5")
    if held:
        bound = max(held)
        if wc is not None and bound >= wc:
            row("warm capacity (p5)", f"{wc}", f">= {bound}", CHECK,
                "held at/above prediction with <5% effective-cold hits (lower bound)")
        else:
            row("warm capacity (p5)", f"{wc}", f">= {bound}", TILDE,
                "lower bound only — eviction not reached")
    else:
        evicted = [r for r in rungs if math.isfinite(r.evict_frac)
                   and r.evict_frac >= 0.05]
        if evicted:
            r0 = min(evicted, key=lambda r: r.pop)
            v = (CROSS if wc is not None and r0.pop < 0.75 * wc else TILDE)
            row("warm capacity (p5)", f"{wc}", f"< ~{r0.pop}", v,
                f"{r0.evict_frac:.0%} of hit turns re-prefilled at {r0.pop} users")
        else:
            row("warm capacity (p5)", f"{wc}", "not separable", TILDE, "no data")

    # miss TTFT level — read at the rung nearest the OPERATING POINT the
    # prediction was computed at (the explorer's Concurrent-users setting):
    # ttft_miss rises steeply with load, so sampling it at the predicted
    # LIMIT instead systematically failed a correct model
    tm = pred.get("ttft_miss_s")
    cand = [r for r in rungs if r.n_miss > 0 and math.isfinite(r.ttft_miss_mean)]
    if cand and tm:
        tgt = (pred.get("operating_point_users")
               or pred.get("predicted_limit_users") or cand[-1].pop)
        r0 = min(cand, key=lambda r: abs(r.pop - tgt))
        ratio = r0.ttft_miss_mean / tm
        v = CHECK if 0.7 <= ratio <= 1.3 else (TILDE if 0.5 <= ratio <= 2.0 else CROSS)
        row("miss mean TTFT", f"{tm:g}s", f"{r0.ttft_miss_mean:.2f}s @ {r0.pop}u",
            v, f"{ratio:.2f}x predicted at the ~{tgt}-user operating point "
               f"(model quotes order-of-magnitude bounds)")
    else:
        row("miss mean TTFT", f"{tm if tm else '-'}", "not separable", TILDE,
            "no forced-miss samples")

    # B* (burst mode only)
    bstar = pred.get("bstar_misses")
    b = state.get("burst")
    if b and b.get("last_ttft_s") is not None:
        within = b["n"] <= (bstar or 0)
        met = b["last_ttft_s"] <= slo["ttft_budget_s"]
        v = CHECK if within == met else (
            TILDE if bstar and 0.75 <= b["n"] / bstar <= 1.33 else CROSS)
        row("B* (burst tolerance)", f"{bstar}",
            f"N={b['n']}: last {b['last_ttft_s']:.2f}s", v,
            ("burst <= B* drained inside budget" if within and met else
             "burst > B* breached budget, as predicted" if not within and not met else
             "outcome contradicts B*"))
    else:
        row("B* (burst tolerance)", f"{bstar}", "not measured", TILDE,
            "run with --burst N to probe the correlated-flush tolerance")

    # ------------------------------------------------------------------
    print("\nWHAT THIS RUN DOES NOT ESTABLISH")
    notes = [
        "Warm capacity is bounded BELOW only: unless a rung shows >5% "
        "effective-cold hit turns, the pool was never driven to eviction, and "
        "the eviction classifier itself is the baseline's 0.4x-cold TTFT "
        "heuristic, not a pool measurement.",
        "Ceilings the ladder did not fail on are 'not separable': one run "
        "observes one binding constraint, not four.",
        "Token counts are chars/{:g} approximations; the achieved/intended "
        "ratio above says how far off — re-run calibrated before trusting "
        "capacity numbers to better than ~15%.".format(args.chars_per_token),
        "Think time is exponential around a fixed mean; real agentic cadence "
        "is burstier (lognormal sigma 2.43 in the measured trace), which "
        "moves the latency ceiling down, not up.",
        "One seed, one window per rung: no variance estimate. Steady state is "
        "assumed after the ramp, not verified.",
        "DP deployments: this drives ONE endpoint; replica-splitting and "
        "session-sticky routing are not exercised.",
    ]
    wl_n = cfg["workload"]
    sub_floor = (wl_n["system_prefix_tokens"]
                 if wl_n.get("sub_shares_prefix", False)
                 else wl_n.get("subagent_prefix_tokens", 3_000))
    if sub_floor >= wl_n["subagent_median_tokens"]:
        notes.append(
            "Subagent leg is DEGENERATE under this config: the prefix floor "
            f"({sub_floor:,} tok) >= the subagent median "
            f"({wl_n['subagent_median_tokens']:,} tok), so most subagent "
            "first turns are byte-identical and vLLM dedups them to one "
            "cache entry — the subagent KV load is not being exercised.")
    if not state.get("burst"):
        notes.append("Correlated-flush tolerance (B*) needs the separate "
                     "--burst mode; the ladder's independent per-turn misses "
                     "cannot see it.")
    for s in notes:
        print(f"  - {s}")

    if args.json:
        out = {
            "config": cfg,
            "rungs": [vars(r) for r in rungs],
            "burst": state.get("burst"),
            "measured_capacity_bracket": [lo, hi],
            "interrupted": interrupted,
        }
        with open(args.json, "w") as f:
            json.dump(out, f, indent=2, default=str)
        print(f"\nraw results written to {args.json}")


# ============================================================================
# ladder construction + dry-run self-check
# ============================================================================
def build_ladder(args, cfg) -> list:
    pred = cfg["predictions"]["predicted_limit_users"]
    mults = [float(x) for x in args.rungs.split(",") if x.strip()]
    pops = {max(1, round(m * pred)) for m in mults}
    # always ladder THROUGH the operating point: ttft_miss_s (and B*) are
    # predictions AT that load, so the verdict needs a rung there
    op = cfg["predictions"].get("operating_point_users")
    if op:
        pops.add(max(1, round(op)))
    return [p for p in sorted(pops) if p <= args.max_users]


def dry_run(args, cfg) -> int:
    """Offline plan + sampler self-check. Exercised in CI-style: exits nonzero
    if the log-normal sampler drifts from its configured median/sigma."""
    wl, slo, pred = cfg["workload"], cfg["slo"], cfg["predictions"]
    ep = cfg["endpoint"]
    print("DRY RUN — plan only, no requests sent\n")
    print(f"endpoint : {args.base_url or ep['base_url']}  "
          f"model={args.model or ep['model']}  "
          f"api key from ${args.api_key_env or ep['api_key_env']}")
    print(f"SLOs     : p{slo['percentile']} TTFT <= {slo['ttft_budget_s']:g}s, "
          f"per-user p50 decode >= {slo['itl_floor_tok_s']:g} tok/s")

    print("\nLOAD LADDER (users; each rung: "
          f"ramp {args.ramp_s:g}s + measure {args.measure_s:g}s)")
    ladder = build_ladder(args, cfg)
    print(f"{'users':>8} {'+sub':>6} {'offered req/s':>14}")
    for pop in ladder:
        n_sub = round(pop * wl["subagent_ratio"])
        print(f"{pop:>8} {n_sub:>6} {(pop + n_sub) / wl['think_time_s']:>14.2f}")
    est = len(ladder) * (args.ramp_s + args.measure_s)
    print(f"full-ladder wall clock (no early stop): ~{est / 60:.0f} min")

    # sampler self-check: the sampled raw median and log-sd must reproduce the
    # configured (median, sigma) — this is the distribution warm capacity and
    # the prefill tail are priced on, so the harness must draw it faithfully
    print("\nPROMPT-LENGTH SAMPLER (n=20,000 per class; tokens, "
          f"clipped to [prefix, {args.context_cap_tokens:,}])")
    rng = random.Random(args.seed)
    failed = False
    hdr = (f"{'class':<10} {'median cfg':>10} {'median smp':>10} "
           f"{'sigma cfg':>9} {'sigma smp':>9} {'p5':>8} {'p50':>8} "
           f"{'p95':>9} {'mean':>9}  check")
    print(hdr)
    # per-class clip floor, mirroring user_loop: subagents clip to THEIR
    # prefix unless sub_shares_prefix — displaying both classes at the user
    # floor overstated the subagent p50 by ~87% under the default config
    sub_floor = (wl["system_prefix_tokens"]
                 if wl.get("sub_shares_prefix", False)
                 else wl.get("subagent_prefix_tokens", 3_000))
    for cls, med, sig, floor in (
            ("user", wl["user_prompt_median_tokens"],
             wl["user_prompt_sigma"], wl["system_prefix_tokens"]),
            ("subagent", wl["subagent_median_tokens"],
             wl["subagent_sigma"], sub_floor)):
        raw = [rng.lognormvariate(math.log(med), sig) for _ in range(20_000)]
        smp_med = pct(raw, 50)
        logs = [math.log(x) for x in raw]
        mu = sum(logs) / len(logs)
        smp_sig = math.sqrt(sum((x - mu) ** 2 for x in logs) / (len(logs) - 1))
        clipped = [min(max(x, floor), args.context_cap_tokens) for x in raw]
        ok = (abs(smp_med / med - 1) < 0.03 and abs(smp_sig / sig - 1) < 0.03)
        failed |= not ok
        print(f"{cls:<10} {med:>10,.0f} {smp_med:>10,.0f} {sig:>9.2f} "
              f"{smp_sig:>9.3f} {pct(clipped, 5):>8,.0f} {pct(clipped, 50):>8,.0f} "
              f"{pct(clipped, 95):>9,.0f} {sum(clipped) / len(clipped):>9,.0f}  "
              f"{'PASS' if ok else 'FAIL'}")
    print(f"(chars per token: {args.chars_per_token:g}; a p50 user prompt is "
          f"~{pct([min(max(x, wl['system_prefix_tokens']), args.context_cap_tokens) for x in [wl['user_prompt_median_tokens']]], 50) * args.chars_per_token / 1e3:,.0f}k chars on the wire)")

    print("\nPREDICTIONS UNDER TEST")
    for k in ("warm_capacity_p5", "decode_ceiling_users", "latency_ceiling_users",
              "saturation_ceiling_users", "binding_constraint",
              "predicted_limit_users", "ttft_miss_s", "bstar_misses",
              "steady_decode_seqs", "steady_decode_tok_s",
              "itl_normal_ms", "itl_worst_freeze_ms"):
        if pred.get(k) is not None:
            print(f"  {k:<26} {pred.get(k)}")
    print("\nHYPOTHESES")
    for h in cfg["hypotheses"]:
        print(f"  - {h}")
    if args.burst:
        burst_pop = args.burst_users or max(1, round(
            pred.get("operating_point_users")
            or 0.5 * pred["predicted_limit_users"]))
        print(f"\n--burst {args.burst}: would run the burst probe instead of "
              f"the ladder (standing load {burst_pop} users)")
    if failed:
        print("\nSAMPLER SELF-CHECK FAILED", file=sys.stderr)
        return 1
    print("\nsampler self-check PASSED; run without --dry-run to measure")
    return 0


# ============================================================================
# main
# ============================================================================
def parse_args(argv=None):
    ap = argparse.ArgumentParser(
        prog="validate_deployment.py",
        description="Closed-loop load harness that tests the capacity model's "
                    "predictions (CONFIG block) against a live vLLM endpoint.",
        epilog="Examples:\n"
               "  uv run validate_deployment.py --dry-run\n"
               "  uv run validate_deployment.py --base-url http://gpu-node:8000/v1\n"
               "  uv run validate_deployment.py --rungs 0.5,1,1.5 --measure-s 300\n"
               "  uv run validate_deployment.py --burst 8 --burst-users 100\n",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base-url", default=None,
                    help="override CONFIG endpoint base URL (e.g. http://host:8000/v1)")
    ap.add_argument("--model", default=None, help="override CONFIG model name")
    ap.add_argument("--api-key-env", default=None,
                    help="env var holding the API key (default: CONFIG's)")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the plan, sampler self-check and hypotheses; "
                         "send nothing (works offline)")
    ap.add_argument("--rungs", default=DEFAULT_RUNGS,
                    help="ladder multipliers of predicted_limit_users "
                         f"(default {DEFAULT_RUNGS})")
    ap.add_argument("--max-users", type=int, default=1024,
                    help="hard cap on any rung's population (default 1024)")
    ap.add_argument("--turns-per-user", type=int, default=0,
                    help="cap turns per session, 0 = unlimited within the window")
    ap.add_argument("--ramp-s", type=float, default=90.0,
                    help="per-rung ramp (sessions establish; not measured) "
                         "(default 90)")
    ap.add_argument("--measure-s", type=float, default=180.0,
                    help="per-rung steady-state measure window (default 180)")
    ap.add_argument("--burst", type=int, default=0, metavar="N",
                    help="run the B* probe instead of the ladder: from steady "
                         "standing load, fire N simultaneous forced misses")
    ap.add_argument("--burst-users", type=int, default=0,
                    help="standing load for --burst (default: "
                         "operating_point_users, else 0.5 x "
                         "predicted_limit_users)")
    ap.add_argument("--chars-per-token", type=float, default=4.0,
                    help="synthetic-text calibration; the report prints the "
                         "achieved ratio to correct it (default 4.0)")
    ap.add_argument("--context-cap-tokens", type=int,
                    # the explorer writes the configuration's own max_seq_len
                    # cap into CONFIG; the flag still overrides it
                    default=CONFIG["workload"].get("context_cap_tokens", 180_000),
                    help="truncation cap on sampled contexts, the model's "
                         "max_seq_len analogue (default: CONFIG, else 180000)")
    ap.add_argument("--request-timeout-s", type=float, default=300.0,
                    help="per-request read timeout; keep well above the TTFT "
                         "budget so breaches are measured, not dropped (default 300)")
    ap.add_argument("--freeze-threshold-ms", type=float, default=250.0,
                    metavar="MS",
                    help="an inter-token gap at or above this counts as a "
                         "FREEZE (default 250). Absolute on purpose: it must "
                         "mean the same thing in both arms of an A/B.")
    ap.add_argument("--seed", type=int, default=0, help="RNG seed (default 0)")
    ap.add_argument("--no-ignore-eos", action="store_true",
                    help="drop the vLLM ignore_eos extension (strict OpenAI "
                         "endpoints); decode tok/s then depends on natural EOS")
    ap.add_argument("--json", default=None, metavar="PATH",
                    help="also write raw rung results as JSON")
    return ap.parse_args(argv)


async def main_async(args, cfg, state: dict):
    import httpx  # lazy: --dry-run must work without any dependency installed

    limits = httpx.Limits(max_connections=4096, max_keepalive_connections=256)
    async with httpx.AsyncClient(limits=limits) as client:
        if args.burst:
            await run_burst(client, args, cfg, state)
            return
        ladder = build_ladder(args, cfg)
        print(f"ladder: {ladder} users "
              f"(ramp {args.ramp_s:g}s + measure {args.measure_s:g}s each)")
        for pop in ladder:
            print(f"\n--- rung: {pop} users ---")
            res = await run_rung(client, args, cfg, pop, state)
            verdict = "PASS" if res.passed else "FAIL (" + "; ".join(res.reasons) + ")"
            print(f"  TTFT hit p50 {fmt(res.ttft_hit_p50, 's')} / miss p50 "
                  f"{fmt(res.ttft_miss_p50, 's')} | all p"
                  f"{cfg['slo']['percentile']} {fmt(res.ttft_all_pX, 's')} | "
                  f"decode p50 {fmt(res.decode_p50, ' tok/s', 1)} | "
                  f"{fmt(res.achieved_rps, ' req/s')} | {verdict}")
            if res.blown:
                print("  SLOs clearly blown — stopping the ladder early "
                      "(higher rungs would only stress the endpoint)")
                break


def main(argv=None) -> int:
    args = parse_args(argv)
    cfg = CONFIG
    if args.dry_run:
        return dry_run(args, cfg)

    # one byte-identical prefix for every session in the process — the whole
    # point: vLLM's prefix cache must be able to dedup it across sessions
    state = {
        "rungs": [],
        "current": None,
        "burst": None,
        "system_prefix": make_text(random.Random(0xC0FFEE),
                                   cfg["workload"]["system_prefix_tokens"],
                                   args.chars_per_token),
        # the subagents' own lean prefix — a DIFFERENT byte-stable block,
        # deduplicated among subagents only (used unless sub_shares_prefix)
        "sub_prefix": make_text(random.Random(0x5AB4EF1C),
                                cfg["workload"].get("subagent_prefix_tokens", 3_000),
                                args.chars_per_token),
    }
    interrupted = False
    try:
        asyncio.run(main_async(args, cfg, state))
    except KeyboardInterrupt:
        interrupted = True
    print_report(state, cfg, args, interrupted=interrupted)
    return 130 if interrupted else 0


if __name__ == "__main__":
    sys.exit(main())
