"""The CONFIG block of a pre-package harness download, kept as a fixture.

The explorer used to hand out a 1,257-line standalone harness with this block
rewritten from the live controls; it now hands out a `workingset.toml`. The
harness itself is gone, but downloads of it are still out there, so
`workingset.config.load_config` still reads a `.py` — and this file is what
pins that reader: a dict literal with comments, `4_096` underscores, implicit
string concatenation, and the `predictions` / `hypotheses` blocks a config
file must never carry.

Trimmed to the CONFIG block; the harness's ~1,200 lines of probe code are the
`workingset.probe` package now. Not importable as a module (there is no
`json` import here on purpose): it is parsed as text, never executed.
"""

# --- BEGIN CONFIG (generated by the interactive explorer) ---
CONFIG = {
    # Reference example: 27B / 4xH200 TP4, f = 1%, max_num_batched_tokens 4096.
    # The explorer replaces this whole block with the configuration on screen.
    "endpoint": {
        "base_url": "http://localhost:8000/v1",
        "model": "Qwen/Qwen3.8-27B-FP8",
        "api_key_env": "VLLM_API_KEY",       # env var NAME, not the key itself
    },
    # what the server under test was started with. Informational: nothing is
    # measured off it, but every prediction below is priced at THIS chunk and
    # the --json dump carries the block, so an A/B run (e.g. 4,096 vs 32,768)
    # is self-labeling.
    "deployment": {
        "gpus": "4xH200",
        "tensor_parallel": 4,
        "replicas": 1,
        "max_num_batched_tokens": 4_096,
        "max_model_len": 180_000,
    },
    "workload": {
        "system_prefix_tokens": 15_000,      # shared prefix, identical bytes for all sessions
        "user_prompt_median_tokens": 31_000, # log-normal median of a user session's context
        "user_prompt_sigma": 0.81,           # log-normal shape (sigma of ln L)
        "warm_turn_tokens": 2_000,           # new tokens appended per warm turn
        "think_time_s": 30.0,                # mean turn-to-turn interval (exponential)
        "subagent_ratio": 0.10,              # subagent sessions per user session
        "subagent_median_tokens": 8_000,
        "subagent_sigma": 0.9,
        "subagent_prefix_tokens": 3_000,     # subagents' own lean shared prefix
        "sub_shares_prefix": False,          # True = subagents reuse the user prefix
        "miss_rate": 0.01,                   # per-turn probability of a forced full re-prefill
        "max_output_tokens": 400,            # decoded tokens per turn (OUT_TOKENS_DEFAULT,
                                             # measured 2026-08-27; was 1,000 assumed)
    },
    "slo": {
        "ttft_budget_s": 10.0,
        "itl_floor_tok_s": 40,               # the study's hard per-user decode floor
        "percentile": 95,                    # TTFT percentile the SLO is read at
    },
    "predictions": {
        "warm_capacity_p5": 403,             # user-class warm sessions, p5 (plan column)
        "decode_ceiling_users": 428,         # users at the 40 tok/s p50 floor (mns@40)
        "latency_ceiling_users": 499,        # users where a miss's mean TTFT = budget
        "saturation_ceiling_users": 509,     # users where prefill duty = 100%
        "binding_constraint": "cache",       # argmin of the four ceilings
        "predicted_limit_users": 403,        # the binding ceiling's value
        "operating_point_users": 64,         # the load ttft_miss_s / bstar were computed AT
        "ttft_miss_s": 0.92,                 # mean TTFT of a miss at the operating point
        "bstar_misses": 9.8,                 # B*: simultaneous misses drained inside the budget
        # H9 (PR #37): the decode batch the LOAD produces, not the all-warm
        # stress point. Arrivals are open-loop, so most of the warm pool is
        # idle between turns and the batch is far smaller / far faster.
        "steady_decode_seqs": 1.15,          # sequences decoding at the operating point
                                             # (re-derived 2026-08-27 at 400 out
                                             # tokens; was 3.11 at the assumed 1,000)
        "steady_decode_tok_s": 817,          # per-user decode at THAT batch size (was 756)
        # the chunk-size hypothesis. Both are per-SSE-event gaps, ms.
        "itl_normal_ms": 2.2,                # gap with no prefill in the pass
        "itl_worst_freeze_ms": 171,          # last chunk of a 180k cold re-prefill
    },
    "hypotheses": [
        "H-cache: >= 403 user sessions stay warm (p5). This run bounds it below "
        "unless load reaches eviction (watch the effective-cold fraction).",
        "H-decode: per-user p50 decode holds >= 40 tok/s up to ~428 concurrent users.",
        "H-latency: a cache miss's mean TTFT reaches the 10 s budget near ~499 users.",
        "H-saturation: prefill duty reaches 100% near ~509 users; above it the queue "
        "has no steady state.",
        "H-binding: the binding constraint is 'cache' — measured SLO capacity should "
        "land near 403 users.",
        "H-ttft-miss: a forced miss's mean TTFT at the operating point is ~0.92 s.",
        "H-burst (needs --burst): a simultaneous flush of <= 9 misses (B* = 9.8) "
        "drains inside the TTFT budget; a larger one does not.",
        # --- the two the reference CONFIG never carried ----------------------
        "H-steady (H9): at the operating point the decode batch holds ~1.2 "
        "sequences at ~817 tok/s each — NOT the whole warm pool at the stress "
        "figure. Read against the measured concurrent-decode count, not the "
        "population. (Re-derived 2026-08-27 at the measured 400 output "
        "tokens; the pre-measurement reference was ~3.1 at ~756.)",
        "H-itl-spike: the worst freeze behind one chunk of a 180k cold "
        "re-prefill is ~171 ms [110-260] at max_num_batched_tokens=4096 vs "
        "~1,289 ms [640-1,980] at 32,768. Brackets are the study's MFU range "
        "([30-60] around 45% when these figures were generated; the bracket "
        "tightened to [35-55] on 2026-08-27, research/prefill.md #1 — the ms "
        "ranges here still quote the wider band): the spike MAGNITUDE "
        "scales ~inversely with MFU and is unvalidated, but the RATIO between "
        "the two settings does not — quote the ratio, not the milliseconds. "
        "Read it on the INTER-TOKEN GAPS table, never on decode p50 (a mean "
        "over the stream is nearly blind to a freeze). NOTE the 4k bracket "
        "straddles a 250 ms freeze threshold, which is why the default is 100 "
        "and why the freeze ladder exists.",
        "H-itl-mean: the normal inter-token gap (~2.2 ms) and total stall time "
        "are ~unchanged between the two chunk settings — prefill FLOPs "
        "telescope, so only the per-pass weight-stream overhead does not "
        "(~+1.9% total machine time at 4k). CAVEAT: the exact invariance is a "
        "property of the flat-MFU pricing; under the per-pass-overhead pricing "
        "the explorer uses, the mean moves by that ~1.9%. Also note ~2.2 ms is "
        "near the client-side timing floor — check the 'floor' column before "
        "reading anything into this row.",
    ],
}
# --- END CONFIG ---
